
export type CapChartOfAccount = {
    accountNumber: string;
    description: string;
};

export const s38ChartOfAccounts: CapChartOfAccount[] = [
    { accountNumber: 'TBA-RB', description: 'Allocated by RB' },
    { accountNumber: 'TBA-NN', description: 'Allocated by NN' },
    { accountNumber: 'TBA-MH', description: 'Allocated by MH' },
    { accountNumber: '1003-01', description: 'Executive Producer' },
    { accountNumber: '1005-01', description: 'Producer' },
    { accountNumber: '1006-01', description: 'Content Producer' },
    { accountNumber: '1006-02', description: 'Editorial Manager' },
    { accountNumber: '1006-04', description: 'Content Editor' },
    { accountNumber: '1012-01', description: 'Insert Producers' },
    { accountNumber: '1036-01', description: 'Journalist & In House Producer' },
    { accountNumber: '1036-02', description: 'Social Media Manager' },
    { accountNumber: '1036-03', description: 'Journalist & In House Producer' },
    { accountNumber: '1037-01', description: 'Consultants' },
    { accountNumber: '1038-01', description: 'Research & Development Fund' },
    { accountNumber: '1038-02', description: 'Investigative Fund' },
    { accountNumber: '1038-03', description: 'Subscription: Online News Publications' },
    { accountNumber: '1038-04', description: 'Subscription: DSTV Stream' },
    { accountNumber: '1038-05', description: 'Lexis Nexis: Windeed Searches' },
    { accountNumber: '1051-01', description: 'Script Producer' },
    { accountNumber: '1105-01', description: 'Retainer' },
    { accountNumber: '1105-02', description: 'Retainer' },
    { accountNumber: '1105-03', description: 'Retainer' },
    { accountNumber: '1105-04', description: 'Retainer' },
    { accountNumber: '1105-05', description: 'Field Presenting - Inserts' },
    { accountNumber: '1105-06', description: 'Studio Presenting' },
    { accountNumber: '1161-01', description: 'Voice Overs - Weekly Teasers & Promos' },
    { accountNumber: '1161-02', description: 'Voice Overs - Teasers' },
    { accountNumber: '1161-03', description: 'Voice Overs - Inserts' },
    { accountNumber: '1161-04', description: 'Voice Overs - Throwforwards & Updates' },
    { accountNumber: '1166-01', description: 'On Camera training' },
    { accountNumber: '1206-01', description: 'Music Producer' },
    { accountNumber: '2023-01', description: 'Production Manager - Broadcast & Finance' },
    { accountNumber: '2023-02', description: 'Production Manager - Shoots, Travel & Crew' },
    { accountNumber: '2024-01', description: 'Production Co-Ordinator - Broadcast & Production' },
    { accountNumber: '2024-02', description: 'Production Co-Ordinator - Archive & Content' },
    { accountNumber: '2131-01', description: 'Studio Director' },
    { accountNumber: '2132-01', description: 'Director\'s Assistant' },
    { accountNumber: '2133-01', description: 'Floor Manager' },
    { accountNumber: '2138-01', description: 'Autocue Operator' },
    { accountNumber: '2161-01', description: 'ENG: DOP (Including Kit & Cam Assistant)' },
    { accountNumber: '2167-02', description: 'Drone: DOP (Including Kit, Gear & Assistant)' },
    { accountNumber: '2357-01', description: 'Set Maintenance' },
    { accountNumber: '2452-01', description: 'Resident Stylist' },
    { accountNumber: '2452-02', description: 'Studio Stylist' },
    { accountNumber: '2473-01', description: 'Wardrobe Purchases' },
    { accountNumber: '2474-01', description: 'Drycleaning Costs' },
    { accountNumber: '2483-01', description: 'Studio Make-Up Artist' },
    { accountNumber: '2496-01', description: 'Masa Kekana Hairpieces' },
    { accountNumber: '3131-01', description: 'Location Fees' },
    { accountNumber: '3131-02', description: 'Location: Editorial Conference' },
    { accountNumber: '3132-01', description: 'Studio Rental' },
    { accountNumber: '3176-01', description: 'Location Security' },
    { accountNumber: '3202-01', description: 'Vehicle Rental (Inserts)' },
    { accountNumber: '3211-02', description: 'Fuel & Oil: Office Generator' },
    { accountNumber: '3212-01', description: 'Parking' },
    { accountNumber: '3213-01', description: 'Toll Fees' },
    { accountNumber: '3215-01', description: 'Shuttle Services: Crew & Cast' },
    { accountNumber: '3216-01', description: 'Mileage & Fuel Claims: Crew' },
    { accountNumber: '3302-01', description: 'Air Tickets: Crew' },
    { accountNumber: '3302-02', description: 'Air Tickets: Editorial Conference' },
    { accountNumber: '3302-03', description: 'Air Tickets: Erin Bates (Studio Anchoring)' },
    { accountNumber: '3305-01', description: 'Air Tickets: Executive Producer' },
    { accountNumber: '3306-01', description: 'Management Fees: Travel Agent' },
    { accountNumber: '3307-01', description: 'Excess Baggage' },
    { accountNumber: '3321-01', description: 'Accommodation: Executive Producer' },
    { accountNumber: '3321-02', description: 'Accommodation: Crew' },
    { accountNumber: '3321-03', description: 'Accommodation: Editorial Conference' },
    { accountNumber: '3331-01', description: 'Craft: Office' },
    { accountNumber: '3331-02', description: 'Catering: Studio' },
    { accountNumber: '3341-01', description: 'Per Diem: Executive Producer' },
    { accountNumber: '3341-02', description: 'Per Diem: Crew' },
    { accountNumber: '4022-01', description: 'Archive Material' },
    { accountNumber: '4022-02', description: 'Foreign Specials' },
    { accountNumber: '4042-01', description: 'Post Production Manager' },
    { accountNumber: '4049-01', description: 'Editor: Senior Resident Inserts' },
    { accountNumber: '4049-02', description: 'Editor: Media & Archive Manager, Promos, Throwforwards & Updates' },
    { accountNumber: '4103-01', description: 'Editor: Freelance Inserts (Including Suite)' },
    { accountNumber: '4104-01', description: 'Edit Suite: In House Inserts' },
    { accountNumber: '4104-02', description: 'Edit Suite: Media Managing & Weekly Editing' },
    { accountNumber: '4105-01', description: 'QC Supervisor' },
    { accountNumber: '4105-02', description: 'Transcripts' },
    { accountNumber: '4109-01', description: 'Edit Server' },
    { accountNumber: '4121-01', description: 'AFM Engineer & Suite: Voice Over Recordings (Weekly Promos & Teasers)' },
    { accountNumber: '4121-02', description: 'AFM Engineer & Suite: Final Mix (Weekly Promos & Teasers)' },
    { accountNumber: '4121-03', description: 'AFM Engineer & Suite: Voice Over Recordings (Standard Insert)' },
    { accountNumber: '4121-04', description: 'AFM Engineer & Suite: Final Mix (Standard Insert)' },
    { accountNumber: '4121-05', description: 'AFM Engineer & Suite: Final Mix (Throwforwards & Updates)' },
    { accountNumber: '4151-01', description: 'External Hard Drives: Backups' },
    { accountNumber: '4151-02', description: 'External Hard Drives: Floating' },
    { accountNumber: '5003-01', description: 'Office Rental & Parking Bays' },
    { accountNumber: '5003-02', description: 'Office Security' },
    { accountNumber: '5003-03', description: 'Office Utilities' },
    { accountNumber: '5003-04', description: 'Office Generator SLA & Maintenance' },
    { accountNumber: '5003-05', description: 'Office Stationary' },
    { accountNumber: '5010-01', description: 'Printer: Monthly Rental (Including Copy Charges)' },
    { accountNumber: '5012-01', description: 'Phones: VOIP, Calls, Storage' },
    { accountNumber: '5012-02', description: 'Mobile Phone Allowances' },
    { accountNumber: '5015-01', description: 'Data Protection' },
    { accountNumber: '5015-02', description: 'Cloud Storage: Sync.com' },
    { accountNumber: '5015-03', description: 'Cloud Storage: Dropbox' },
    { accountNumber: '5016-01', description: 'Software: Production - Microsoft 365' },
    { accountNumber: '5016-02', description: 'Software: Production - Vimeo' },
    { accountNumber: '5016-03', description: 'Software: Production - Google' },
    { accountNumber: '5016-04', description: 'Software: Production - Canva' },
    { accountNumber: '5016-06', description: 'Software: Production - Jotform' },
    { accountNumber: '5016-07', description: 'Software: Production - MailChimp' },
    { accountNumber: '5016-08', description: 'Software: Production - Xneelo' },
    { accountNumber: '5016-09', description: 'Software: Post Production - Adobe' },
    { accountNumber: '5016-10', description: 'Software: Post Production - Envato' },
    { accountNumber: '5016-11', description: 'Software: Post Production - Frame.io' },
    { accountNumber: '5016-12', description: 'Software: Post Production - WeTransfer' },
    { accountNumber: '5016-13', description: 'IT Support' },
    { accountNumber: '5019-01', description: 'Bank Charges: Normal' },
    { accountNumber: '5025-01', description: 'Accounting: External Independent Accounting Firm' },
    { accountNumber: '5026-01', description: 'Software: Accounting - SAGE One Accounting' },
    { accountNumber: '5026-02', description: 'Software: Accounting - SAGE ONE Payroll' },
    { accountNumber: '6103-01', description: 'SDL Expense' },
    { accountNumber: '6104-01', description: 'COIDA Expense' },
    { accountNumber: '6105-01', description: 'UIF Expense' },
    { accountNumber: '6302-01', description: 'Insurance' },
    { accountNumber: '6403-01', description: 'Production Fees: 1st 50%' },
    { accountNumber: '6403-02', description: 'Production Fees: 2nd 50%' },
];

export const capChartOfAccounts: CapChartOfAccount[] = [
    { accountNumber: 'TBA/001', description: 'To be allocated by RB' },
    { accountNumber: 'TBA/002', description: 'To be allocated by NN' },
    { accountNumber: 'TBA/003', description: 'To be allocated by MH' },
    { accountNumber: '1000/000', description: 'Sales' },
    { accountNumber: '2000/000', description: 'Purchases' },
    { accountNumber: '2100/000', description: 'Inventory Adjustment' },
    { accountNumber: '2150/000', description: 'Inventory Count Variance' },
    { accountNumber: '2200/000', description: 'Purchase Variance' },
    { accountNumber: '2250/000', description: 'Operating expenses' },
    { accountNumber: '2400/000', description: 'Recovery Account' },
    { accountNumber: '2700/000', description: 'Discount Recieved' },
    { accountNumber: '2750/000', description: 'Interest Received' },
    { accountNumber: '2800/000', description: 'Pft/Loss on Sale of Non Current Assets' },
    { accountNumber: '2850/000', description: 'Bad Debts Recovered' },
    { accountNumber: '2900/000', description: 'Sundry Income' },
    { accountNumber: '3000/000', description: 'Accounting Fees' },
    { accountNumber: '3050/000', description: 'Advertising' },
    { accountNumber: '3150/000', description: 'Bad Debts' },
    { accountNumber: '3200/000', description: 'Bank Charges' },
    { accountNumber: '3250/000', description: 'Cleaning' },
    { accountNumber: '3300/000', description: 'Computer Expenses' },
    { accountNumber: '3350/000', description: 'Consulting Fees' },
    { accountNumber: '3400/000', description: 'Courier & Postage' },
    { accountNumber: '3450/000', description: 'Depreciation' },
    { accountNumber: '3550/000', description: 'Discount Allowed' },
    { accountNumber: '3600/000', description: 'Donations' },
    { accountNumber: '3650/000', description: 'Electricity & Water' },
    { accountNumber: '3700/000', description: 'Entertainment' },
    { accountNumber: '3750/000', description: 'Finance Charges' },
    { accountNumber: '3800/000', description: 'General Expenses' },
    { accountNumber: '3850/000', description: 'Insurance' },
    { accountNumber: '3900/000', description: 'Interest Paid' },
    { accountNumber: '3950/000', description: 'Leasing Charges' },
    { accountNumber: '4000/000', description: 'Legal Fees' },
    { accountNumber: '4050/000', description: 'Levies' },
    { accountNumber: '4150/000', description: 'Motor Vehicle Expenses' },
    { accountNumber: '4200/000', description: 'Printing & Stationery' },
    { accountNumber: '4210/000', description: 'Pft/Loss on foreign exchange' },
    { accountNumber: '4300/000', description: 'Rent paid' },
    { accountNumber: '4350/000', description: 'Repairs & Maintenance' },
    { accountNumber: '4375/000', description: 'Business Development' },
    { accountNumber: '4400/000', description: 'Salaries & Wages' },
    { accountNumber: '4450/000', description: 'Staff Training' },
    { accountNumber: '4500/000', description: 'Staff Welfare' },
    { accountNumber: '4550/000', description: 'Subscriptions' },
    { accountNumber: '4600/000', description: 'Telephone & Internet' },
    { accountNumber: '4650/000', description: 'Travel & Accommodation' },
    { accountNumber: '4700/000', description: 'Subsistence and Travel' },
    { accountNumber: '4800/001', description: 'Staff Uniforms' },
    { accountNumber: '4800/002', description: 'Shop Expenses' },
    { accountNumber: '4800/003', description: 'Consumable Materials' },
    { accountNumber: '4800/004', description: 'Directors Remuneration' },
    { accountNumber: '4800/005', description: 'Security' },
    { accountNumber: '4800/006', description: 'Small Assets' },
    { accountNumber: '4800/007', description: 'Sundry Expenses' },
    { accountNumber: '4800/008', description: 'Income Tax Expense' },
    { accountNumber: '4900/001', description: 'Fuel' },
    { accountNumber: '4900/002', description: 'Commission' },
    { accountNumber: '4900/500', description: 'CBMADT Expenses' },
    { accountNumber: '5200/000', description: 'Retained earnings' },
    { accountNumber: '5500/000', description: 'Long Term Liabilities' },
    { accountNumber: '5600/000', description: 'Installment Sale Creditors' },
    { accountNumber: '5700/000', description: 'Medical Expenses' },
    { accountNumber: '6100/010', description: 'Land & Buildings - @ Cost' },
    { accountNumber: '6100/020', description: 'Land & Buildings - Accum Depre' },
    { accountNumber: '6200/010', description: 'Motor Vehicles - @ Cost' },
    { accountNumber: '6200/020', description: 'Motor Vehicles - Accum Depre' },
    { accountNumber: '6250/010', description: 'Computer Equipment - @ Cost' },
    { accountNumber: '6250/020', description: 'Computer Equipment - Accum Depre' },
    { accountNumber: '6300/010', description: 'Office Equipment - @ Cost' },
    { accountNumber: '6300/020', description: 'Office Equipment - Accum Depre' },
    { accountNumber: '6350/010', description: 'Furniture & Fittings - @ Cost' },
    { accountNumber: '6350/020', description: 'Furniture & Fittings - Accum Depre' },
    { accountNumber: '6600/010', description: 'Fixed assets, at cost' },
    { accountNumber: '6600/020', description: 'Fixed assets, accumulated depreciation' },
    { accountNumber: '7000/000', description: 'Goodwill / Intangible Assets' },
    { accountNumber: '7100/000', description: 'Investments' },
    { accountNumber: '8200/000', description: 'Sundry Customers' },
    { accountNumber: '9000/000', description: 'Supplier Control Account' },
    { accountNumber: '9100/000', description: 'GRN Accrual Account' },
    { accountNumber: '9200/000', description: 'Sundry Suppliers' },
    { accountNumber: '9400/000', description: 'Provision for Future Expenses' },
    { accountNumber: '9400/010', description: 'Provision for Insurance' },
    { accountNumber: '9400/020', description: 'Provision for Salary Bonus' },
    { accountNumber: '9500/000', description: 'Vat / Tax Control Account' },
    { accountNumber: '9500/001', description: 'Share Holder loan' },
    { accountNumber: '9510/000', description: 'Vat / Tax Provision Account' },
    { accountNumber: '9990/001', description: 'Provision for Accounting Fee' },
    { accountNumber: '9990/002', description: 'VAT Payable' },
    { accountNumber: '9990/003', description: 'Income Tax Payable' },
    { accountNumber: '9990/004', description: 'Term Loans' },
    { accountNumber: '9990/005', description: 'Opening Balance Clearing' },
];

export const s39ChartOfAccounts: CapChartOfAccount[] = [
    { accountNumber: 'TBA-RB', description: 'Allocated by RB' },
    { accountNumber: 'TBA-NN', description: 'Allocated by NN' },
    { accountNumber: 'TBA-MH', description: 'Allocated by MH' },
    { accountNumber: '1003-01', description: 'Executive Producer' },
    { accountNumber: '1005-01', description: 'Producer' },
    { accountNumber: '1006-01', description: 'Editorial Manager' },
    { accountNumber: '1006-02', description: 'Content Editor' },
    { accountNumber: '1012-01', description: 'Insert Producers' },
    { accountNumber: '1036-01', description: 'Social Media & Online Editor' },
    { accountNumber: '1036-02', description: 'Junior In House Producer' },
    { accountNumber: '1037-01', description: 'Viewer Panel Consultants' },
    { accountNumber: '1038-01', description: 'Research & Development Fund' },
    { accountNumber: '1038-02', description: 'Investigative Fund' },
    { accountNumber: '1038-03', description: 'Subscription: Online News Publications' },
    { accountNumber: '1038-04', description: 'Subscription: DSTV Stream' },
    { accountNumber: '1038-05', description: 'Lexis Nexis: Windeed Searches' },
    { accountNumber: '1105-01', description: 'Presenter Retainer' },
    { accountNumber: '1105-02', description: 'Presenter Retainer' },
    { accountNumber: '1105-03', description: 'Presenter Retainer' },
    { accountNumber: '1105-04', description: 'Presenter Retainer' },
    { accountNumber: '1105-05', description: 'Field Presenting: Inserts' },
    { accountNumber: '1105-06', description: 'Studio Presenting: Live Shows' },
    { accountNumber: '1161-01', description: 'Voice Overs: Weekly Teasers - English' },
    { accountNumber: '1161-02', description: 'Voice Overs: Weekly Teasers - Afrikaans' },
    { accountNumber: '1161-03', description: 'Voice Overs: Inserts - Guest Presenters' },
    { accountNumber: '1161-04', description: 'Voice Overs: Throwforwards & Updates' },
    { accountNumber: '2023-01', description: 'Operational Manager' },
    { accountNumber: '2023-02', description: 'Production Manager' },
    { accountNumber: '2024-01', description: 'Production Co-Ordinator: Broadcast' },
    { accountNumber: '2024-02', description: 'Production Co-Ordinator: Archive' },
    { accountNumber: '2131-01', description: 'Studio Director: Live Studio' },
    { accountNumber: '2131-02', description: 'Studio Director: Script Meetings' },
    { accountNumber: '2132-01', description: 'Director\'s Assistant: Live Studio' },
    { accountNumber: '2133-01', description: 'Floor Manager: Live Studio' },
    { accountNumber: '2138-01', description: 'Autocue Operator: Live Studio' },
    { accountNumber: '2161-01', description: 'ENG DOP (Full Kit & Assistant)' },
    { accountNumber: '2167-02', description: 'Drone DOP (Full Kit & Permits)' },
    { accountNumber: '2357-01', description: 'Set Maintenance' },
    { accountNumber: '2452-01', description: 'Resident Stylist: Field & Live Studio' },
    { accountNumber: '2473-01', description: 'Wardrobe Purchases' },
    { accountNumber: '2474-01', description: 'Dry Cleaning Costs' },
    { accountNumber: '2483-01', description: 'Make-Up Artist: Live Studio' },
    { accountNumber: '2496-01', description: 'Hair Pieces: Masa Kekana' },
    { accountNumber: '3131-01', description: 'Location Fees' },
    { accountNumber: '3131-02', description: 'Location: Editorial Conference' },
    { accountNumber: '3132-01', description: 'Studio Rental: Live Studio' },
    { accountNumber: '3176-01', description: 'Location Security' },
    { accountNumber: '3202-01', description: 'Vehicle Rental: Inserts' },
    { accountNumber: '3211-01', description: 'Fuel & Oil: Office Generator' },
    { accountNumber: '3212-01', description: 'Parking: Inserts' },
    { accountNumber: '3213-01', description: 'Toll Fees: Inserts' },
    { accountNumber: '3215-01', description: 'Shuttle Services: Crew, Cast, EP' },
    { accountNumber: '3216-01', description: 'Mileage & Fuel Claims: Inserts' },
    { accountNumber: '3302-01', description: 'Air Tickets: Inserts' },
    { accountNumber: '3302-02', description: 'Air Tickets: Editorial Conference' },
    { accountNumber: '3302-03', description: 'Air Tickets: Studio Anchoring Erin Bates' },
    { accountNumber: '3305-01', description: 'Air Tickets: Executive Producer' },
    { accountNumber: '3306-01', description: 'Management Fees: Travel Agent' },
    { accountNumber: '3307-01', description: 'Excess Baggage' },
    { accountNumber: '3321-01', description: 'Accommodation: Executive Producer' },
    { accountNumber: '3321-02', description: 'Accommodation: Inserts' },
    { accountNumber: '3321-03', description: 'Accommodation: Editorial Conference' },
    { accountNumber: '3331-01', description: 'Craft: Office' },
    { accountNumber: '3331-02', description: 'Catering: Studio' },
    { accountNumber: '3341-01', description: 'Per Diem: Executive Producer' },
    { accountNumber: '3341-02', description: 'Per Diem: Inserts' },
    { accountNumber: '4022-01', description: 'Archive Material' },
    { accountNumber: '4022-02', description: 'Foreign Specials' },
    { accountNumber: '4049-01', description: 'Editor: Weekly Deliveries' },
    { accountNumber: '4049-02', description: 'Editor: Inserts Internal' },
    { accountNumber: '4103-01', description: 'Editor: Inserts Freelance' },
    { accountNumber: '4104-01', description: 'Edit Suite: Internal Inserts' },
    { accountNumber: '4104-02', description: 'Edit Suite: Weekly Deliveries' },
    { accountNumber: '4105-01', description: 'Transcripts: External & Internal' },
    { accountNumber: '4121-01', description: 'AFM: VO Recordings - Promos & Teasers (Engineer & Suite)' },
    { accountNumber: '4121-02', description: 'AFM: Final Mix - Promos & Teasers (Engineer & Suite)' },
    { accountNumber: '4121-03', description: 'AFM: VO Recordings - Inserts (Engineer & Suite)' },
    { accountNumber: '4121-04', description: 'AFM: Final Mix - Inserts (Engineer & Suite)' },
    { accountNumber: '4121-05', description: 'AFM: VO & Final Mix - Throwforwards & Updates' },
    { accountNumber: '4151-01', description: 'External Hard Drives: Backups' },
    { accountNumber: '5003-01', description: 'Rent: Office & Parking Bays' },
    { accountNumber: '5003-02', description: 'Security: Office' },
    { accountNumber: '5003-03', description: 'Utilities: Office' },
    { accountNumber: '5003-04', description: 'Generator: SLA & Maintenance' },
    { accountNumber: '5003-05', description: 'Stationary & Courier: Office' },
    { accountNumber: '5010-01', description: 'Printer: Rental & Copy Charges' },
    { accountNumber: '5012-01', description: 'Phones: VOIP, Calls, Storage' },
    { accountNumber: '5012-02', description: 'Phones: Mobile Allowance' },
    { accountNumber: '5015-01', description: 'Data Protection' },
    { accountNumber: '5015-02', description: 'Cloud Storage: Sync.com' },
    { accountNumber: '5015-03', description: 'Cloud Storage: Dropbox' },
    { accountNumber: '5016-01', description: 'Software: Production - Microsoft 365' },
    { accountNumber: '5016-02', description: 'Software: Production - Vimeo' },
    { accountNumber: '5016-03', description: 'Software: Production - Google' },
    { accountNumber: '5016-04', description: 'Software: Production - Canva' },
    { accountNumber: '5016-05', description: 'Software: Production - Jotform' },
    { accountNumber: '5016-06', description: 'Software: Production - MailChimp' },
    { accountNumber: '5016-07', description: 'Software: Production - Xneelo' },
    { accountNumber: '5016-08', description: 'Software: Post Production - Adobe' },
    { accountNumber: '5016-09', description: 'Software: Post Production - Envato' },
    { accountNumber: '5016-10', description: 'Software: Post Production - Frame.io' },
    { accountNumber: '5016-11', description: 'Software: Post Production - Smash' },
    { accountNumber: '5016-12', description: 'IT Support' },
    { accountNumber: '5016-13', description: 'Offsite Server Storage' },
    { accountNumber: '5019-01', description: 'Bank Charges: Normal & Foreign' },
    { accountNumber: '5025-01', description: 'Accounting: Independent Accounting Firm' },
    { accountNumber: '5026-01', description: 'Software: Accounting - SAGE One Accounting' },
    { accountNumber: '5026-02', description: 'Software: Accounting - SAGE One Payroll' },
    { accountNumber: '6103-01', description: 'SDL Expense' },
    { accountNumber: '6104-01', description: 'COIDA Expense' },
    { accountNumber: '6105-01', description: 'UIF Expense' },
    { accountNumber: '6302-01', description: 'Insurance' },
    { accountNumber: '6403-01', description: 'Production Fees: 1st 50%' },
    { accountNumber: '6403-02', description: 'Production Fees: 2nd 50%' },
];

export const goChartOfAccounts: CapChartOfAccount[] = [
    { accountNumber: '1006-00', description: 'ASSOCIATE PRODUCER - SNR' },
    { accountNumber: '1008-00', description: 'SERIES PRODUCER - SNR' },
    { accountNumber: '1031-00', description: 'RESEARCHER - HOD' },
    { accountNumber: '1036-00', description: 'JOURNALIST - SNR' },
    { accountNumber: '1102-00', description: 'PRESENTERS - SERIES' },
    { accountNumber: '3131-00', description: 'LOCATION FEES - ' },
    { accountNumber: '3176-00', description: 'SECURITY - LOCATION' },
    { accountNumber: '3121-00', description: 'UNIT MANAGER - HOD' },
    { accountNumber: '3211-00', description: 'FUEL & OIL - PRODUCTION VEHICLES' },
    { accountNumber: '3202-00', description: 'VEHICLE - CREW DRIVER' },
    { accountNumber: '3341-00', description: 'PER DIEM / S&T - CREW' },
    { accountNumber: '3302-00', description: 'AIR TICKET (REGIONAL RSA) - CREW' },
    { accountNumber: '3307-00', description: 'EXCESS BAGGAGE - CREW' },
    { accountNumber: '3321-00', description: 'ACCOMMODATION - CREW' },
    { accountNumber: '3331-00', description: 'CATERING - ON THE ROAD' },
    { accountNumber: '3331-00', description: 'CATERING - ON SET' },
    { accountNumber: '5017-00', description: 'BANK CHARGES - NORMAL' },
    { accountNumber: '6302-00', description: 'INSURANCE - UMBRELLA LIABILITY' },
    { accountNumber: '6403-00', description: 'PRODUCTION FEE - FINAL PAYMENT' },
    { accountNumber: '2161-00', description: 'DOP / CAMERA HOD - SNR' },
    { accountNumber: '2162-00', description: 'CAMERA OPERATOR - SNR' },
    { accountNumber: '2184-00', description: 'CONSUMABLES - CAMERA - ' },
    { accountNumber: '2193-00', description: 'SOUND RECORDIST - SNR' },
    { accountNumber: '2212-00', description: 'CONSUMABLES - SOUND - ' },
    { accountNumber: '2021-00', description: 'LINE PRODUCER - SNR' },
    { accountNumber: '2052-00', description: 'PRODUCTION ACCOUNTANT - SNR' },
    { accountNumber: '2452-00', description: 'STYLIST - SNR' },
    { accountNumber: '2471-00', description: 'WARDROBE PURCHASES - ' },
    { accountNumber: '4051-00', description: 'EDITOR (OFFLINE) - SNR' },
    { accountNumber: '4052-00', description: 'EDITOR (ONLINE / GRADING) - SNR' },
    { accountNumber: '4105-00', description: 'EDIT COST - TRANSCRIPTS' },
    { accountNumber: '4105-00', description: 'EDIT COST - SUBTITLES' },
    { accountNumber: '4151-00', description: 'STOCK - HARD DRIVE 10TB' },
    { accountNumber: '4121-00', description: 'AUDIO EDIT - FINAL MIX ENGINEER' },
];
